### ISSUE TITLE
1st Sprint Second Team meeting

### ISSUE THREAD

**Issue by lily-law** [chingu-voyages/v16-geckos-team-02#15]
- [ ] discuss and agree on MPV's
- [ ] come up with a name/logo idea
- [ ] talk about git workflow [Chingu guide for workflow](https://voyage.docs.chingu.io/project/workflow)
- [ ] decide on coding style guide
- [ ] check current issues progress (learning svelte...)
- [ ] assign issues to team members
